### ISSUE TITLE
能抓取赚客吧的新帖子吗

### ISSUE THREAD

**Issue by pingshu** [liuyunfz/DingTalkBot#3]
http://www.zuanke8.com/forum-15-1.html

**Comment by liuyunfz** [comment]
您好，感谢您的提议。我已经访问查看了你所提出的“赚客吧”，它是一个基于Discuz!的论坛网站，按照你的要求如果要获取它的新帖子我觉得应该并不难。唯一麻烦的是该网站获取具体信息需要有账号，且部分帖子需要“果果”来提高阅读权限。这对于编写代码者来说或许并不麻烦，但需要使用者额外提供自己的权限账号才能进行正常的获取。
而现在，我需要明确您的需求，您所提供给我的链接是刚注册的用户无权限访问的，所以我并未能成功看到里面的内容。所以我不太清楚您需要获得的新帖子是哪个板块的新帖子，亦或是其他的内容，希望能得到您的具体回复。感谢您的支持。

**Comment by pingshu** [comment]
是“赚客大家谈”板块
![D4155D32-D55A-4623-B38F-C12D9BEBB071](https://user-images.githubusercontent.com/22138807/95029576-b2a9a980-06db-11eb-8041-db8b60b58912.jpeg)

**Comment by pingshu** [comment]
能否做到隔几分钟抓取一次新帖子，然后只把新帖子的标题推送到钉钉上，谢谢

**Comment by liuyunfz** [comment]
您好，感谢您的回复，我已了解了您的需求。按照我的猜测，您所提出的功能应该不难实现，只需要使用者额外提供账号即可。而唯一的问题则是作为一个新功能，考虑到用户的差异性，可能并不是所有人都需要这个功能，所以我打算将其作为模块类来丰富主文件的功能，同时这样也可以更好的应付之后其他人可能提出的需求。
而目前要将功能化作主代码的各个附加模块，则需要我重新书写代码的整体框架，而现在我却没有很好的思路，这也是目前的主要障碍。
总的来说，很感谢您的建议，但基于我目前的水平有限，我需要一段时间思考能否修改整体的框架结构，亦或是暂时放弃这个功能的添加。我会进行尝试，并在近段时间内与您进行联系，希望能得到你的谅解。

**Comment by pingshu** [comment]
找到这个，不知有没有帮助

https://github.com/Faterli/zuanke8-post

**Comment by liuyunfz** [comment]
感谢，我现在正在对该库以及网站进行研究。但是因为我缺少有足够权限的账号，为了确保功能无误，希望您能够与我联系，方便我进行测试，也为了更好的满足你的需求。
QQ:957843164
WeChat:liuyunfz

**Comment by liuyunfz** [comment]
# 预实现功能：

- 完成对赚客吧的内容爬取，并且通过钉钉进行通知。

- 要求间隔一分钟。

# 任务难点：

- 赚客吧需要用户登陆才可进行查看具体内容.

- 赚客吧的用户登陆中的密码传输使用了md5算法。

- 一分钟间隔与GitHub action中间执行间隔造成的可能误差。

# 最终方案：

由于GitHub action的额度限制，以及考虑到误差，将频率改成了五分钟。因为尚无将功能模块化的思路，考虑到各种原因，在原代码的基础上进行定制创建了新的分支并交付委托人。  

# 想法与已发现的bug

- python input输入会忽略“^”字符

- 一分钟一次GitHub action唤醒可能会导致误差，但可以尝试只唤醒一次使用while true保持python运行，sleep一分钟后继续执行。而阻碍则是GitHub action的额度，不能一直启动action。

---
鉴于要求的功能已大致实现，其他内容基于现在的水平尚无法实现，遂将本issue关闭。
